name: wechat-bot

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wechat-bot:latest

    - name: Save Docker image as tar file
      run: docker save wechat-bot:latest -o wechat-bot.tar

    - name: Upload Docker image to release
      uses: softprops/action-gh-release@v2
      with:
          name: "Latest Release"
          tag: "latest"
          commit: ${{ github.sha }}
          allowUpdates: true  # 允许多次更新 latest 的内容
          replacesArtifacts: true  # 替换旧文件
          artifacts: "wechat-bot.tar"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
